#ifndef LANG_H
#define LANG_H

#include <Arduino.h>
#include <avr/pgmspace.h>

#include "config.h"

// OLED text resources. Keep strings short to fit the 128x64 display and AVR flash.
#if SERVO_TESTER_LANGUAGE == SERVO_TESTER_LANG_CZ
#define TXT_UNIT_A F(" A")
#define TXT_UNIT_MA F(" mA")
#define TXT_ALERT_CRIT F("CR")
#define TXT_ALERT_WARN F("WR")
#define TXT_ALERT_NONE F("--")
#define TXT_HEADER_MODE F("M:")
#define TXT_HEADER_POWER F("NAP:")
#define TXT_POWER_HV F("HV")
#define TXT_POWER_STD F("STD")
#define TXT_BOOT F("Startuji...")
#define TXT_SCREEN_STATUS F("STAV")
#define TXT_SCREEN_GAUGE F("UKAZ")
#define TXT_SCREEN_CURRENT F("PROUD")
#define TXT_SCREEN_VBUS F("VBUS")
#define TXT_SCREEN_PEAK F("MAX")
#define TXT_PULSE F("Pulz:")
#define TXT_US F("us")
#define TXT_ANGLE F("Uhel:")
#define TXT_DEG F("deg")
#define TXT_RANGE F("Rozsah:")
#define TXT_DASH F("-")
#define TXT_REVERSE F("Rev:")
#define TXT_ON "ZAP"
#define TXT_OFF "VYP"
#define TXT_LEFT F("L:")
#define TXT_COUNT F("Cnt:")
#define TXT_HINT_MODE F("U/D:Mod")
#define TXT_PERCENT F("%")
#define TXT_INA_NOT_FOUND F("INA3221 nenalezen")
#define TXT_CHECK_I2C F("Zkontroluj I2C")
#define TXT_CH1 F("CH1: ")
#define TXT_CH2 F("CH2: ")
#define TXT_CH3 F("CH3: ")
#define TXT_HINT_NEXT_MENU F("S:Dalsi H:Menu")
#define TXT_V_DROOP F("V d")
#define TXT_CH1_MAX F("CH1 max:")
#define TXT_CH2_MAX F("CH2 max:")
#define TXT_CH3_MAX F("CH3 max:")
#define TXT_SETTINGS F("Nastaveni")
#define TXT_EDIT F("EDIT")
#define TXT_HINT_EDIT F("U/D:Hod SEL:OK")
#define TXT_HINT_NAV F("U/D:Pol SEL:OK")
#define TXT_FMT_MIN_PULSE PSTR("Min pulz: %u")
#define TXT_FMT_MAX_PULSE PSTR("Max pulz: %u")
#define TXT_FMT_REVERSE PSTR("Reverse: %s")
#define TXT_FMT_SWEEP_CYCLE PSTR("Sweep: %u.%us")
#define TXT_FMT_BURN_CYCLES PSTR("Burn: %u")
#define TXT_FMT_SAVE_EXIT PSTR("Ulozit a zpet")
#define TXT_FMT_CANCEL PSTR("Zrusit")
#else
#define TXT_UNIT_A F(" A")
#define TXT_UNIT_MA F(" mA")
#define TXT_ALERT_CRIT F("CR")
#define TXT_ALERT_WARN F("WR")
#define TXT_ALERT_NONE F("--")
#define TXT_HEADER_MODE F("M:")
#define TXT_HEADER_POWER F("PWR:")
#define TXT_POWER_HV F("HV")
#define TXT_POWER_STD F("STD")
#define TXT_BOOT F("Starting...")
#define TXT_SCREEN_STATUS F("STATUS")
#define TXT_SCREEN_GAUGE F("GAUGE")
#define TXT_SCREEN_CURRENT F("CURRENT")
#define TXT_SCREEN_VBUS F("VBUS")
#define TXT_SCREEN_PEAK F("PEAK")
#define TXT_PULSE F("Pulse:")
#define TXT_US F("us")
#define TXT_ANGLE F("Angle:")
#define TXT_DEG F("deg")
#define TXT_RANGE F("Range:")
#define TXT_DASH F("-")
#define TXT_REVERSE F("Rev:")
#define TXT_ON "ON"
#define TXT_OFF "OFF"
#define TXT_LEFT F("L:")
#define TXT_COUNT F("Cnt:")
#define TXT_HINT_MODE F("U/D:Mode")
#define TXT_PERCENT F("%")
#define TXT_INA_NOT_FOUND F("INA3221 not found")
#define TXT_CHECK_I2C F("Check I2C wiring")
#define TXT_CH1 F("CH1: ")
#define TXT_CH2 F("CH2: ")
#define TXT_CH3 F("CH3: ")
#define TXT_HINT_NEXT_MENU F("S:Next H:Menu")
#define TXT_V_DROOP F("V d")
#define TXT_CH1_MAX F("CH1 max:")
#define TXT_CH2_MAX F("CH2 max:")
#define TXT_CH3_MAX F("CH3 max:")
#define TXT_SETTINGS F("Settings")
#define TXT_EDIT F("EDIT")
#define TXT_HINT_EDIT F("U/D:Val SEL:Done")
#define TXT_HINT_NAV F("U/D:Item SEL:OK")
#define TXT_FMT_MIN_PULSE PSTR("Min pulse: %u")
#define TXT_FMT_MAX_PULSE PSTR("Max pulse: %u")
#define TXT_FMT_REVERSE PSTR("Reverse: %s")
#define TXT_FMT_SWEEP_CYCLE PSTR("Sweep cycle: %u.%us")
#define TXT_FMT_BURN_CYCLES PSTR("Burn cycles: %u")
#define TXT_FMT_SAVE_EXIT PSTR("Save & exit")
#define TXT_FMT_CANCEL PSTR("Cancel")
#endif

#endif
